set_property PACKAGE_PIN D7 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property PACKAGE_PIN F8 [get_ports reset_n]
set_property PACKAGE_PIN G1 [get_ports TCLK]
set_property PACKAGE_PIN F1 [get_ports Vsync]
set_property PACKAGE_PIN E4 [get_ports Hsync]
set_property PACKAGE_PIN E3 [get_ports DE]
set_property PACKAGE_PIN E1 [get_ports Tpower]
set_property PACKAGE_PIN R3 [get_ports {R[7]}]
set_property PACKAGE_PIN U2 [get_ports {R[6]}]
set_property PACKAGE_PIN U1 [get_ports {R[5]}]
set_property PACKAGE_PIN T3 [get_ports {R[4]}]
set_property PACKAGE_PIN T2 [get_ports {R[3]}]
set_property PACKAGE_PIN M1 [get_ports {G[7]}]
set_property PACKAGE_PIN M5 [get_ports {G[6]}]
set_property PACKAGE_PIN M4 [get_ports {G[5]}]
set_property PACKAGE_PIN L2 [get_ports {G[4]}]
set_property PACKAGE_PIN L1 [get_ports {G[3]}]
set_property PACKAGE_PIN P3 [get_ports {G[2]}]
set_property PACKAGE_PIN N2 [get_ports {B[7]}]
set_property PACKAGE_PIN P1 [get_ports {B[6]}]
set_property PACKAGE_PIN N5 [get_ports {B[5]}]
set_property PACKAGE_PIN N4 [get_ports {B[4]}]
set_property PACKAGE_PIN M2 [get_ports {B[3]}]

set_property PACKAGE_PIN A6 [get_ports SW]

set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 26]]
set_property IOSTANDARD LVCMOS12 [get_ports -of_objects [get_iobanks 65]]
